# Generated by Django 5.2.6 on 2025-09-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_event_exact_time_event_extra_time_match_referee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='registration_by_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
