# Generated by Django 5.2.6 on 2025-09-16 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_tournament_registration_by_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
