# Generated by Django 5.2.6 on 2025-09-30 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_team_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='start_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tagozat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='color',
            field=models.CharField(blank=True, help_text='Custom team color in hex format (e.g., #FF5733)', max_length=7, null=True),
        ),
    ]
