# Generated by Django 5.2.6 on 2025-09-30 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_player_start_year_player_tagozat_team_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kozlemeny',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Cím')),
                ('content', models.TextField(verbose_name='Tartalom')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Létrehozás ideje')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Módosítás ideje')),
                ('active', models.BooleanField(default=True, verbose_name='Aktív')),
                ('priority', models.CharField(choices=[('low', 'Alacsony'), ('normal', 'Normál'), ('high', 'Magas'), ('urgent', 'Sürgős')], default='normal', max_length=10, verbose_name='Prioritás')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.profile', verbose_name='Szerző')),
            ],
            options={
                'verbose_name': 'Közlemény',
                'verbose_name_plural': 'Közlemények',
                'ordering': ['-priority', '-date_created'],
            },
        ),
    ]
