# Generated by Django 5.2.6 on 2025-09-30 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_kozlemeny'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='half',
            field=models.IntegerField(blank=True, choices=[(1, '1st Half'), (2, '2nd Half')], null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='minute_extra_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
