# Generated by Django 5.2.6 on 2025-09-30 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_team_logo_url_photo_match_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='description',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='title',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='uploaded_by',
        ),
    ]
