# Generated by Django 5.2.6 on 2025-10-02 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_photo_description_remove_photo_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Szankcio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minus_points', models.IntegerField(verbose_name='Pontlevonás')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Indoklás')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Létrehozás ideje')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.team', verbose_name='Csapat')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tournament', verbose_name='Bajnokság')),
            ],
            options={
                'verbose_name': 'Szankció',
                'verbose_name_plural': 'Szankciók',
                'ordering': ['-date_created'],
            },
        ),
    ]
