# Generated by Django 5.2.7 on 2025-11-25 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_szankcio'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('cancelled_new_date', 'Cancelled - New Date to be Published'), ('cancelled_no_date', 'Cancelled - New Date not to be Published')], default='active', max_length=20, null=True),
        ),
    ]
