# Generated by Django 5.2.7 on 2025-11-26 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_match_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('match_start', 'Match Start'), ('goal', 'Goal'), ('own_goal', 'Own Goal'), ('yellow_card', 'Yellow Card'), ('red_card', 'Red Card'), ('half_time', 'Half Time'), ('full_time', 'Full Time'), ('extra_time', 'Extra Time'), ('match_end', 'Match End')], max_length=20),
        ),
    ]
